PROCESS BEFORE OUTPUT.
*&SPWIZARD: PBO FLOW LOGIC FOR TABSTRIP 'SO'
  MODULE so_active_tab_set.
  CALL SUBSCREEN so_sca
    INCLUDING g_so-prog g_so-subscreen.
* MODULE STATUS_0901.
*

PROCESS AFTER INPUT.
*&SPWIZARD: PAI FLOW LOGIC FOR TABSTRIP 'SO'
  CALL SUBSCREEN so_sca.
  MODULE so_active_tab_get.
* MODULE USER_COMMAND_0901.
